### ISSUE TITLE
The --print-computed-version flag output is incorrect

### ISSUE THREAD

**Issue by KealanM** [sstarcher/helm-release#18]
When you supply the --print-computed-version the version print to stdout is incorrect as it does not factor in the git commits, sha or branch naming elements. 

Example
```
helm release ./helm/test --print-computed-version
0.2.1

helm release ./helm/test
INFO[0000] updating the Chart.yaml to version 0.2.1-0.development+c409e7f
```

Is this intended? It would appear some changes to the logic after that flag was introduced changed the order of calls and resulted in the printed version being incorrect. But just want to check.

**Comment by sstarcher** [comment]
I'm currently trying to fathom why I did it that way.

The current --print-computed-version is relying on the bump flag.

**Comment by sstarcher** [comment]
Can you see if the above works as you expect?

**Comment by KealanM** [comment]
That looks exactly like the way i had a fix on a fork, I was just waiting on legal to be allowed contrib back. Thanks for the fix :).
