### ISSUE TITLE
Flag to print version.

### ISSUE THREAD

**Issue by jeff-french** [sstarcher/helm-release#2]
It would be handy to have something like `helm release --print-version` that would calculate the version and print it to standard out so that the version number could be used by other commands / scripts as part of a CI pipeline.

**Comment by makkalot** [comment]
I was about to open a similar issue :) Would be nice to have that functionality so can compute docker image versions as well in CI. If there's interest happy to create MR for it ;)

**Comment by sstarcher** [comment]
I entirely missed these notifications.  I'll get that flag in this weekend.  @jeff-french sorry about that.
