### ISSUE TITLE
How can we stop it from updating the appVersion in the charts.yaml

### ISSUE THREAD

**Issue by Galileo1** [sstarcher/helm-release#24]
Any idea??

**Comment by sstarcher** [comment]
So the request is for the app version to but be versioned with the chart? If so I can add a flag.

**Comment by Galileo1** [comment]
Yeah! we keep out helm charts separate from code base. Chart Version and App Version being same is good only when they are published for same branch or tag. It would be good to have toggle/flag to choose  whether app version in Chart.yaml should get updated or not

**Comment by sstarcher** [comment]
When not updating the appVersion I'm guessing you also don't need to update values.yaml's image.tag value.  Is that correct?

**Comment by sstarcher** [comment]
@Galileo1 checkout the PR and let me know if that accomplishes what you wanted.

**Comment by Galileo1** [comment]
true!! we don't want to update the image tag aswell.  sounds good to me.
