### ISSUE TITLE
Question: Installation on linux distribution using tar file 

### ISSUE THREAD

**Issue by Galileo1** [sstarcher/helm-release#26]
Background: 
I am sitting behind corporate proxy. I can use helm plugin install command, give it the git hub url and install it on my local machine. But I can't install plugins using `helm plugin install` command in docker images. Because images get built on (Jenkins boxes that cannot talk to internet) and published on internal artifactory/nexus. So I have to upload the tar file from your release page into artifactory and then use curl it in Dockerfile. 

Difference:
1. When I use `helm plugin install ` in local machine it gets the whole source code and binaries in the HELM_HOME/.cache/helm/plugins. And creates a symlink in HELM_HOME/.local/share/helm/plugins. Next command `helm plugin list` works fine.

2. When I download the tar.gz file and untar it into HELM_HOME/.local/share/helm/plugins in Dockerfile. Next command `helm plugin list` skips listing this `helm release` plugin. However it lists all other plugins. And the installation for all other plugins follow the same pattern(Download tar -> untar in HELM_HOME.local/share/helm/plugins -> list the plugin using `helm plugin list` command).

Doe you see anything wrong in there.

I have attached the snapshot below -

![helm plugin issue](https://user-images.githubusercontent.com/9716232/80032852-e0d96980-853f-11ea-9e2e-c3ddbc281543.png)

```
 curl -kLO https://artifactory2.xxx.xxx.xxx/helm-plugins/helm-release/v0.3.2/helm-release_0.3.2_linux_amd64.tar.gz \
    && mkdir -p ${XDG_DATA_HOME}/helm/plugins \
    && helm-release_0.3.2_linux_amd64.tar.gz -C ${XDG_DATA_HOME}/helm/plugins \
    && chmod 777 ${HELM_HOME} \
    && rm -rf *.tar.gz \
    && helm plugin list 
```

**Comment by sstarcher** [comment]
I have not tried this method.  Maybe for the second stop try untaring it into the cache directory and creating a symlink.

**Comment by Galileo1** [comment]
I am going to try that now

**Comment by Galileo1** [comment]
No luck!! with symlink 

![helm plugin issue2](https://user-images.githubusercontent.com/9716232/80037277-63195c00-8547-11ea-987b-026e6dd3beaf.png)

**Comment by sstarcher** [comment]
I'll try your install method this weekend and see what I can find out.  Let me know if you have any luck finding out why it's not working like the other plugins.

**Comment by Galileo1** [comment]
I wounder if `helm plugin list` would need anything else to read the metadata about the plugin. The only difference I can see between helm-release and others(helm-diff, helm-git) where all of these were installed using the tar file. 

> Others - have got all the src code with binary 

![helm plugin issue 3](https://user-images.githubusercontent.com/9716232/80146775-78a18b00-8606-11ea-976b-81091e0a541a.png)

> helm-release - have got just the binary

![helm plugin issue 4](https://user-images.githubusercontent.com/9716232/80146806-8820d400-8606-11ea-89b2-d724c427864c.png)

Even when you install helm-release using `helm plugin install` command in local. It copies all the src code and binary. That works fine.
Not sure if could be the reason.

**Comment by sstarcher** [comment]
try tossing the plugin.yaml into othe same direcctory

**Comment by sstarcher** [comment]
Try the latest 0.3.3 release. 
I also added instructions - https://github.com/sstarcher/helm-release/blob/master/README.md#install-without-internet

**Comment by Galileo1** [comment]
this work fine. Just one thing I noticed - when I updated the plugin to 0.3.3 . It still show 0.3.2 in `helm plugin list` command. I checked that this has got latest flag which you added  but still shows 0.3.2. 

![hlem plugin works](https://user-images.githubusercontent.com/9716232/80331187-7a37b100-889b-11ea-9510-c980477e313e.png)

**Comment by sstarcher** [comment]
Thanks, the plugin.yaml is not setup in my release process yet and I forgot to bump the version.  You should be good to go now.
