### ISSUE TITLE
Question - versioning during release

### ISSUE THREAD

**Issue by Galileo1** [sstarcher/helm-release#27]
Just a question - when the source is git. And you want to create a major release how do you do it? Any kind of examples/ good practice to version helm charts would be good. 

- Features branch generates NXT-TAG-BRANCH-NAME-COMMIT+SHA
- Merge to master branch generates COMMIT+SHA
- Is it possible to specify a flag to bump the version to 1.0.0+COMMIT+SHA?

**Comment by sstarcher** [comment]
Everything for master is based off the prior tags.  So if you tag `1.0.0` and you merge something new into master the value generated by helm-release would be `1.0.0-1+SHA`.

For updating tags I use a snippet  that looks like this
```
    git checkout master
    git pull
    TAG=$(helm-release . --print-computed-version --bump patch)
    git tag -a -m 'tagging release' $TAG
    git push origin $TAG
```

Let me know how I could improve the documentation to help.

**Comment by Galileo1** [comment]
Thank! for answering the question. I think documentation is fine.we were using jgitver plugin to version the helm charts. Until I bumped into your library. I objective of moving to this plugin is to reduce the complexity of versioning and ppl who do not know maven/pom concepts they do need unnecessarily learn them. jgitver also work on same fundamentals good from maven project but not right choice for helm. I wonder why helm release and helm publish are not baked in helm. But really appreciate your work and thanks! again for your contribution towards community.

**Comment by sstarcher** [comment]
Thanks, let me know if I can do anything to make this better!
