### ISSUE TITLE
Documentation missing -s option

### ISSUE THREAD

**Issue by iosdal** [sstarcher/helm-release#28]
Dear,
referring to 
[this](https://github.com/sstarcher/helm-release/pull/25)
the option -s is not documented in Readme usage.
So 
`helm release CHART - Would determine the next tag for the chart and update the Chart.yaml`
is not true. Without passsing the -s flag it will update both Chart and values.
Thanks,

Ivan

**Comment by sstarcher** [comment]
Thanks, does this fix it properly - https://github.com/sstarcher/helm-release/commit/a2f4cd07966da2a485a1f7a5e862465740c7b81b
