### ISSUE TITLE
Private URL for GitHub in dependency file

### ISSUE THREAD

**Issue by mrothroc** [sstarcher/helm-release#4]
The dependencies listed in .gitmodules use the ssh URL which requires the user to be able to log in as "sstarcher".  This creates an error "Unexpected error while defensively updating submodules" when you try to install the helm plugin.

According to this article:
https://stackoverflow.com/questions/8197089/fatal-error-when-updating-submodule-using-git

they should instead use the public URL.

For example, this:
url = git@github.com:sstarcher/helm-release-tags.git

should probably be this:
url = https://github.com/helm-release-tags.git

**Comment by sstarcher** [comment]
It would require you to have any SSH key that is valid for GitHub, but you are correct it would be better to use HTTP.  I'll get that fixed thanks for catching this issue.
