### ISSUE TITLE
Versioning Control

### ISSUE THREAD

**Issue by brunohms** [sstarcher/helm-release#6]
Is it possible to send a parameter to the plugin so that it decides how to upgrade the version?
Instead of using git.

I want to do this because I have a git repository with multiple charts.
So I would like to do something like `helm release CHART major` to increase the major version.

**Comment by sstarcher** [comment]
So you want to take the current version that is specified in the chart and have it bump major/minor/patch based on the command?

It's certainly possible to add that feature, but currently, the way it's written is everything comes from git.

**Comment by sstarcher** [comment]
Let me know if you are still interested and I'll try and get this feature in.

**Comment by brunohms** [comment]
@sstarcher Thanks for being interested in adding it as a feature.
However since I've created this issue I went venturing myself with go and actually developed an application that does this.

Haven't published it yet...

Would you be interested in "merging" both applications so that there is one application that is able to handle chart versions in multiple ways?

**Comment by brunohms** [comment]
I will fork helm-release and try to add my code here.
I'll let you know when I'm done

**Comment by jurgenweber** [comment]
@brunohms I have the same use case, about 5 charts in one repo. How are you going with it?

**Comment by brunohms** [comment]
@jurgenweber kind of mannually...
I did create a go program to help me with this, but stoped developing charts in the place where I work...

I will try to add a repo with my current implementations and post the link for it here.

Wanted to merge what I did with this repo but had no time for it =/

**Comment by brunohms** [comment]
@jurgenweber take a look at: https://github.com/brunohms/multichart-helm-release

@sstarcher if you may take a look at it as well would be helpful

**Comment by sstarcher** [comment]
I'll see if I have a hour this weekend to add this feature.

**Comment by sstarcher** [comment]
@jurgenweber want to test this out for me to see if it meets your needs - https://github.com/sstarcher/helm-release/pull/13

**Comment by sstarcher** [comment]
This should now be resolved.
