### ISSUE TITLE
Question: are subcharts supported?

### ISSUE THREAD

**Issue by GianniGiglio** [sstarcher/helm-release#8]
Trying to use the plugin with a chart containing subcharts:

cmd: helm release . patch

INFO[0000] found more than a single chart in the following paths -
	.
	charts/gateway
	charts/sba
Error: plugin "release" exited with error

**Comment by sstarcher** [comment]
Yep, that would be a bug let me fix that for you.

**Comment by sstarcher** [comment]
https://github.com/sstarcher/helm-release/pull/10

**Comment by sstarcher** [comment]
A new release of 0.2.2 was just cut.
